# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lnka < Formula
  desc "CLI tool for managing symlinks with interactive Terminal UI"
  homepage "https://github.com/marco-arnold/lnka"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.3/lnka_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "4b14a77aa64239d1d75d13cf5586bb4c5752654c98f312c4e6c862711a72b2be"

      def install
        bin.install "lnka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.3/lnka_1.0.3_Darwin_arm64.tar.gz"
      sha256 "bbbb14fd6cc5ce06d2ef2f65738e71ed9b12c59eda74c2e0e68203150dc6481a"

      def install
        bin.install "lnka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.3/lnka_1.0.3_Linux_x86_64.tar.gz"
      sha256 "948fa52160d2308f63e501fb1d8060abf42b460d2731125cc4f740a783dc50f2"
      def install
        bin.install "lnka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.3/lnka_1.0.3_Linux_arm64.tar.gz"
      sha256 "01f4302c64947284d7a23a96f6a8af477352101f787c366bd875c03f08e6bf1a"
      def install
        bin.install "lnka"
      end
    end
  end

  test do
    system "#{bin}/lnka", "--version"
  end
end
