# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lnka < Formula
  desc "CLI tool for managing symlinks with interactive Terminal UI"
  homepage "https://github.com/marco-arnold/lnka"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.2/lnka_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "0f5cba5183e467ba281f47f0c8ecfec3e297dfa66c6118acaccf2e741a7a6117"

      def install
        bin.install "lnka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.2/lnka_1.0.2_Darwin_arm64.tar.gz"
      sha256 "dbc487006253ccfc663c0e2158afb5a9e11965f6e11ed279f020e2294795bc52"

      def install
        bin.install "lnka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.2/lnka_1.0.2_Linux_x86_64.tar.gz"
      sha256 "39d8a3d1160d138dddaf5dfbb8e8029261aacbe7b5ca1e255439317285efcb20"
      def install
        bin.install "lnka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.2/lnka_1.0.2_Linux_arm64.tar.gz"
      sha256 "9c3dc962bc0360d6d942cd010ac2534b62306cfe5cff97fa8afa1555d5ffa76d"
      def install
        bin.install "lnka"
      end
    end
  end

  test do
    system "#{bin}/lnka", "--version"
  end
end
