# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lnka < Formula
  desc "CLI tool for managing symlinks with interactive Terminal UI"
  homepage "https://github.com/marco-arnold/lnka"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.1/lnka_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "c12a6adf33a4329d1e6769a9dc45400d2f6473176ce6f0284d0537a30ca4a6b7"

      def install
        bin.install "lnka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.1/lnka_1.0.1_Darwin_arm64.tar.gz"
      sha256 "48ba035230f29b23b0ca7e4c83956bc5ab06137ea40d60cd749aaf642e68c25d"

      def install
        bin.install "lnka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.1/lnka_1.0.1_Linux_x86_64.tar.gz"
      sha256 "5a013eacd9732c66e3634e3480d7b169345247020c17ee737d57f883d4cc0987"
      def install
        bin.install "lnka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marco-arnold/lnka/releases/download/v1.0.1/lnka_1.0.1_Linux_arm64.tar.gz"
      sha256 "ad5249c49a21e516d9d2662ba5e3853244c0c876a266210377760b4eb13f8638"
      def install
        bin.install "lnka"
      end
    end
  end

  test do
    system "#{bin}/lnka", "--version"
  end
end
