# This file was generated by GoReleaser. DO NOT EDIT.
cask "lnka" do
  name "lnka"
  desc "CLI tool for managing symlinks with interactive Terminal UI"
  homepage "https://github.com/marco-arnold/lnka"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lnka"

  on_macos do
    on_intel do
      url "https://github.com/marco-arnold/lnka/releases/download/v#{version}/lnka_#{version}_Darwin_x86_64.tar.gz"
      sha256 "93a8f6cecb329c187806cf854d8cc6af49b937a6c9525e13896b7719e921337c"
    end
    on_arm do
      url "https://github.com/marco-arnold/lnka/releases/download/v#{version}/lnka_#{version}_Darwin_arm64.tar.gz"
      sha256 "0d20821868dfb52ce8429076f5b553463ce7ec845d834d312410d1677fecd76d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marco-arnold/lnka/releases/download/v#{version}/lnka_#{version}_Linux_x86_64.tar.gz"
      sha256 "a65370aa3d4b1b5386f38fd647843478835babbf3b1e236469d3e25ffaa586c4"
    end
    on_arm do
      url "https://github.com/marco-arnold/lnka/releases/download/v#{version}/lnka_#{version}_Linux_arm64.tar.gz"
      sha256 "b4366985e5a566e05941b894105e774b23e7b35685a5675011711df76eb046ff"
    end
  end

  # No zap stanza required
end
